name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{cpp,h} | xargs clang-format -i --verbose src/chessviz/main.cpp src/libchessviz/lib.cpp src/libchessviz/lib.h && git diff --exit-code

      - name: Test
        run: make test && ./bin/chess-test

      - name: Build application
        run: make
